/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package variable_static;

/**
 *
 * @author Jorge
 */
public class Ventana extends javax.swing.JFrame {


    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContador = new javax.swing.JTextField();
        cmdmas = new javax.swing.JButton();
        cmdmenos = new javax.swing.JButton();
        cmdREINICIAR = new javax.swing.JButton();
        lblTITULO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtContador.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtContador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContador.setText("0");
        txtContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContadorActionPerformed(evt);
            }
        });

        cmdmas.setText("+");
        cmdmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdmasActionPerformed(evt);
            }
        });

        cmdmenos.setText("-");
        cmdmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdmenosActionPerformed(evt);
            }
        });

        cmdREINICIAR.setText("REINICIAR");
        cmdREINICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdREINICIARActionPerformed(evt);
            }
        });

        lblTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITULO.setText("CONTADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTITULO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cmdmenos)
                        .addGap(18, 18, 18)
                        .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdmas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(cmdREINICIAR)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdREINICIAR)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdmas)
                    .addComponent(cmdmenos))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdmasActionPerformed
        // Obtener el texto del campo de texto txtContador y almacenarlo en una cadena
        String cnt = txtContador.getText();

        // Convertir la cadena cnt en un entero
        int c = Integer.parseInt(cnt);

        // Incrementar el valor del entero
        c++;

        // Actualizar el texto del campo de texto con el nuevo valor
        txtContador.setText(String.valueOf(c));

    }//GEN-LAST:event_cmdmasActionPerformed

    private void txtContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContadorActionPerformed

    private void cmdmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdmenosActionPerformed
        // Obtener el texto del campo de texto txtContador y almacenarlo en una cadena
        String cnt = txtContador.getText();

        // Convertir la cadena cnt en un entero
        int c = Integer.parseInt(cnt);

        // Incrementar el valor del entero
        c--;

        // Actualizar el texto del campo de texto con el nuevo valor
        txtContador.setText(String.valueOf(c));
    }//GEN-LAST:event_cmdmenosActionPerformed

    private void cmdREINICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdREINICIARActionPerformed
       txtContador.setText(0+"");
    }//GEN-LAST:event_cmdREINICIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdREINICIAR;
    private javax.swing.JButton cmdmas;
    private javax.swing.JButton cmdmenos;
    private javax.swing.JLabel lblTITULO;
    private javax.swing.JTextField txtContador;
    // End of variables declaration//GEN-END:variables
}
