/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pseint;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Jorge
 */
public class VentanaEjemplo2_8 extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo2_17
     */
    public VentanaEjemplo2_8() {
        initComponents();
        personalizarVentana();
    }
    public void personalizarVentana() {
        ImageIcon icono = new ImageIcon("image/cross1.png");
        Image image = icono.getImage();
        this.setIconImage(image);//Cambiar el icono de la ventana

        this.setTitle("GUI SWING");
        this.setResizable(false); //No se redimensione
        this.setLocationRelativeTo(null);//Colocar la ventana en el centro de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTITULO = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cmdCantidad1 = new javax.swing.JButton();
        cmdCantidad2 = new javax.swing.JButton();
        cmdCantidad3 = new javax.swing.JButton();
        cmdCantidad4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtSueldoFinal = new javax.swing.JTextField();
        botReiniciar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTITULO.setBackground(new java.awt.Color(0, 0, 0));
        lblTITULO.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lblTITULO.setForeground(new java.awt.Color(255, 255, 255));
        lblTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITULO.setText("CALCULAR SU SUELDO FINAL");
        lblTITULO.setOpaque(true);

        lblSueldo.setText("INGRESE SU SUELDO");

        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });

        cmdCantidad1.setText("15%");
        cmdCantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantidad1ActionPerformed(evt);
            }
        });

        cmdCantidad2.setText("10%");
        cmdCantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantidad2ActionPerformed(evt);
            }
        });

        cmdCantidad3.setText("8%");
        cmdCantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantidad3ActionPerformed(evt);
            }
        });

        cmdCantidad4.setText("5%");
        cmdCantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantidad4ActionPerformed(evt);
            }
        });

        jLabel1.setText("AUMENTA SU SUELDO EN :");

        txtSueldoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoFinalActionPerformed(evt);
            }
        });

        botReiniciar.setText("REINICIAR");
        botReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botReiniciarActionPerformed(evt);
            }
        });

        lblTotal.setText("TOTAL =");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdCantidad1)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCantidad2)
                        .addGap(28, 28, 28)
                        .addComponent(cmdCantidad3)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCantidad4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTITULO, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addComponent(jSeparator1))))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(botReiniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSueldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCantidad1)
                    .addComponent(cmdCantidad2)
                    .addComponent(cmdCantidad3)
                    .addComponent(cmdCantidad4))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblTotal)
                .addGap(18, 18, 18)
                .addComponent(txtSueldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botReiniciar)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSueldoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoFinalActionPerformed

    private void cmdCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantidad1ActionPerformed
        //VARIABLES Y ENTRADA
        String sueldo = txtSueldo.getText();
        double s = Double.parseDouble(sueldo);
        //proceso
        double sf = s * 1.15;
        //salida
        txtSueldoFinal.setText(String.valueOf(sf + " euros"));
     
    }//GEN-LAST:event_cmdCantidad1ActionPerformed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void cmdCantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantidad2ActionPerformed
    //VARIABLES Y ENTRADA
        String sueldo = txtSueldo.getText();
        double s = Double.parseDouble(sueldo);
        //proceso
        double sf = s * 1.10;
        //salida
        txtSueldoFinal.setText(String.valueOf(sf + " euros"));
    }//GEN-LAST:event_cmdCantidad2ActionPerformed

    private void cmdCantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantidad3ActionPerformed
      //VARIABLES Y ENTRADA
        String sueldo = txtSueldo.getText();
        double s = Double.parseDouble(sueldo);
        //proceso
        double sf = s * 1.08;
        //salida
        txtSueldoFinal.setText(String.valueOf(sf + " euros"));
    }//GEN-LAST:event_cmdCantidad3ActionPerformed

    private void cmdCantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantidad4ActionPerformed
      //VARIABLES Y ENTRADA
        String sueldo = txtSueldo.getText();
        double s = Double.parseDouble(sueldo);
        //proceso
        double sf = s * 1.05;
        //salida
        txtSueldoFinal.setText(String.valueOf(sf + " euros"));
    }//GEN-LAST:event_cmdCantidad4ActionPerformed

    private void botReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botReiniciarActionPerformed
     txtSueldoFinal.setText("");
     txtSueldo.setText("");
    }//GEN-LAST:event_botReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEjemplo2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEjemplo2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEjemplo2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEjemplo2_8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEjemplo2_8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botReiniciar;
    private javax.swing.JButton cmdCantidad1;
    private javax.swing.JButton cmdCantidad2;
    private javax.swing.JButton cmdCantidad3;
    private javax.swing.JButton cmdCantidad4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JLabel lblTITULO;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtSueldoFinal;
    // End of variables declaration//GEN-END:variables
}
