/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pseint;

import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class Ventana3_20 extends javax.swing.JFrame {
 
    DefaultListModel dlm = new DefaultListModel();
    
    public Ventana3_20() {
        initComponents();
        personalizarVentana();
        lstFactorial.setModel(dlm);
    }
    public void personalizarVentana() {
        ImageIcon icono = new ImageIcon("image/cross1.png");
        Image image = icono.getImage();
        this.setIconImage(image);//Cambiar el icono de la ventana

        this.setTitle("GUI SWING");
        this.setResizable(false); //No se redimensione
        this.setLocationRelativeTo(null);//Colocar la ventana en el centro de la pantalla
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTITULO = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblMensaje = new javax.swing.JLabel();
        txtFactorial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFactorial = new javax.swing.JList<>();
        jSeparator3 = new javax.swing.JSeparator();
        cmdNuevo = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        cmdCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 630));
        setMinimumSize(new java.awt.Dimension(400, 630));
        setSize(new java.awt.Dimension(400, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTITULO.setBackground(new java.awt.Color(0, 0, 0));
        lblTITULO.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lblTITULO.setForeground(new java.awt.Color(255, 255, 255));
        lblTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITULO.setText("FACTORIAL DE NUMERO");
        lblTITULO.setOpaque(true);
        getContentPane().add(lblTITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 22));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 400, 10));

        lblNumero.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("INGRESAR UN NUMERO ENTERO POSITIVO");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 290, -1));

        txtNumero.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 400, 10));

        lblMensaje.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("MENSAJE");
        getContentPane().add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 290, -1));

        txtFactorial.setEditable(false);
        txtFactorial.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtFactorial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactorialActionPerformed(evt);
            }
        });
        getContentPane().add(txtFactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 30));

        lstFactorial.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lstFactorial.setForeground(new java.awt.Color(255, 0, 51));
        lstFactorial.setEnabled(false);
        jScrollPane1.setViewportView(lstFactorial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 220, 220));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 400, -1));

        cmdNuevo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cmdNuevo.setText("NUEVO");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(cmdNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        cmdSalir.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cmdSalir.setText("SALIR");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        getContentPane().add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        cmdCalcular.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cmdCalcular.setText("CALCULAR");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactorialActionPerformed

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
         txtNumero.setText("");
         txtFactorial.setText("");
         dlm.clear();

    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
       dlm.clear();
       String ns = txtNumero.getText();
       String patron = "[0-9]+";
       boolean correcto = ns.matches(patron);
       int f =1;
       if(correcto){
           long n = Long.parseLong(ns);
           if(n!=0){
               for(int i = 1; i<=n; i++){
                   f = f * i; 
                   dlm.addElement(f);
               }
               lblMensaje.setText("FACTORIAL DISTINTO CERO");
               txtFactorial.setText(f + "");
               
           }else {
               f = 1;
               lblMensaje.setText("FACTORIAL CERO");
               txtFactorial.setText(f + "");
           }
           
       }else {
           JOptionPane.showMessageDialog(null, "NUMERO INCORRECTO", "ERROR", JOptionPane.ERROR_MESSAGE);
           
       }

    }//GEN-LAST:event_cmdCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3_20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3_20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3_20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3_20.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3_20().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTITULO;
    private javax.swing.JList<String> lstFactorial;
    private javax.swing.JTextField txtFactorial;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
